function addOption(i,t,v){var x=document.getElementById(i);var option=document.createElement("option");option.text=t;option.value=v;x.add(option);}
var weekday=new Array(7);weekday[0]="Sunday";weekday[1]="Monday";weekday[2]="Tuesday";weekday[3]="Wednesday";weekday[4]="Thursday";weekday[5]="Friday";weekday[6]="Saturday";var month=new Array();month[0]="January";month[1]="February";month[2]="March";month[3]="April";month[4]="May";month[5]="June";month[6]="July";month[7]="August";month[8]="September";month[9]="October";month[10]="November";month[11]="December";var day;function gday(n){day=n;if(day==1){day=day+"st"}
else if(day==2){day=day+"nd"}
else if(day==3){day=day+"rd"}
else if(day==21){day=day+"st"}
else if(day==22){day=day+"nd"}
else if(day==23){day=day+"rd"}
else if(day==31){day=day+"st"}
else{day=day+"th"}
return day;}
function DateFormat(date){var dd=date.getDate();var mm=date.getMonth()+1;var yyyy=date.getFullYear();if(dd<10){dd='0'+dd}
if(mm<10){mm='0'+mm}
return mm+'/'+dd+'/'+yyyy;}
function TimeFormat1(date){var hour=date.getHours();var minute=date.getMinutes();var amPM=(hour>11)?"pm":"am";if(hour>12){hour-=12;}else if(hour==0){hour="12";}
if(minute<10){minute="0"+minute;}
return hour+":"+minute+" "+amPM;}
function TimeFormat2(date){var hour=date.getHours();var minute=date.getMinutes();if(hour<10){hour="0"+hour;}
if(minute<10){minute="0"+minute;}
return ""+hour+minute;}
Date.prototype.stdTimezoneOffset=function(){var jan=new Date(this.getFullYear(),0,1);var jul=new Date(this.getFullYear(),6,1);return Math.max(jan.getTimezoneOffset(),jul.getTimezoneOffset());}
Date.prototype.dst=function(){return this.getTimezoneOffset()<this.stdTimezoneOffset();}
var est_offset=((new Date()).dst())?-4:-5;var d=new Date();var d_utc=d.getTime()+(d.getTimezoneOffset()*60000);d=new Date(d_utc+(3600000*est_offset));var d1=new Date();var d2=new Date();var d3=new Date();var d4=new Date();d1.setDate(d.getDate());d2.setDate(d.getDate()+1);d3.setDate(d.getDate()+2);d4.setDate(d.getDate()+3);var t1=new Date(d.getFullYear(),d.getMonth(),d.getDate(),7,0,0);var t2=new Date(d.getFullYear(),d.getMonth(),d.getDate(),13,0,0);var t3=new Date(d.getFullYear(),d.getMonth(),d.getDate(),17,0,0);var t4=new Date(d.getFullYear(),d.getMonth(),d.getDate(),20,0,0);function setupCountdownTimer(nextSession){var currentTime=new Date().getTime();var duration=nextSession-currentTime;var durationInHours=duration/(60*60*1000);countDownTimer(durationInHours);}
var jit_interval=0;var min_interval=30;var now=new Date();var nextWebinarTime;var today=0;if((t4.getTime()-d.getTime())/60000>min_interval){today=1;}else{today=0;}
$(document).ready(function(){var coeff=1000*60*jit_interval;if(jit_interval>0){nextWebinarTime=new Date(Math.ceil(now.getTime()/coeff)*coeff);}else{nextWebinarTime=new Date();}
nextWebinarTime_utc=nextWebinarTime.getTime()+(nextWebinarTime.getTimezoneOffset()*60000);nextWebinarTime_est=new Date(nextWebinarTime_utc+(3600000*est_offset));if(jit_interval>0&&nextWebinarTime_est>=t1&&(t4.getTime()-nextWebinarTime_est.getTime())/60000>min_interval){if((t1.getTime()-d.getTime())/60000>min_interval){if(nextWebinarTime_est>t1){nextWebinarTime_est=new Date(t1.getTime());}}else if((t2.getTime()-d.getTime())/60000>min_interval){if(nextWebinarTime_est>t2){nextWebinarTime_est=new Date(t2.getTime());}}else if((t3.getTime()-d.getTime())/60000>min_interval){if(nextWebinarTime_est>t3){nextWebinarTime_est=new Date(t3.getTime());}}else if((t4.getTime()-d.getTime())/60000>min_interval){if(nextWebinarTime_est>t4){nextWebinarTime_est=new Date(t4.getTime());}}else{var d2t1=new Date(t1.getTime());d2t1.setDate(d2.getDate());if(nextWebinarTime_est>d2t1){nextWebinarTime_est=new Date(d2t1.getTime());}}}else{if((t1.getTime()-d.getTime())/60000>min_interval){nextWebinarTime_est=new Date(t1.getTime());}else if((t2.getTime()-d.getTime())/60000>min_interval){nextWebinarTime_est=new Date(t2.getTime());}else if((t3.getTime()-d.getTime())/60000>min_interval){nextWebinarTime_est=new Date(t3.getTime());}else if((t4.getTime()-d.getTime())/60000>min_interval){nextWebinarTime_est=new Date(t4.getTime());}else{nextWebinarTime_est=new Date(t1.getTime());nextWebinarTime_est.setDate(d2.getDate());}}
nextWebinarTime_utc=nextWebinarTime_est.getTime()-(est_offset*3600000);nextWebinarTime=new Date(nextWebinarTime_utc-(nextWebinarTime.getTimezoneOffset()*60000));setupCountdownTimer(nextWebinarTime);if(today==1){addOption("webinar_dates","Select your Date","");addOption("webinar_dates",weekday[d1.getDay()]+", "+month[d1.getMonth()]+" "+gday(d1.getDate()),DateFormat(d1));addOption("webinar_dates",weekday[d2.getDay()]+", "+month[d2.getMonth()]+" "+gday(d2.getDate()),DateFormat(d2));addOption("webinar_dates",weekday[d3.getDay()]+", "+month[d3.getMonth()]+" "+gday(d3.getDate()),DateFormat(d3));}else{addOption("webinar_dates","Select your Date","");addOption("webinar_dates",weekday[d2.getDay()]+", "+month[d2.getMonth()]+" "+gday(d2.getDate()),DateFormat(d2));addOption("webinar_dates",weekday[d3.getDay()]+", "+month[d3.getMonth()]+" "+gday(d3.getDate()),DateFormat(d3));addOption("webinar_dates",weekday[d4.getDay()]+", "+month[d4.getMonth()]+" "+gday(d4.getDate()),DateFormat(d4));}});function dateSelect(){document.getElementById("webinar_times").options.length=0;if(document.getElementById("webinar_dates").value!=""){if((today==1)&&(document.getElementById("webinar_dates").selectedIndex==1)){addOption("webinar_times","Select your Time","");addOption("webinar_times",TimeFormat1(nextWebinarTime_est)+" (US Eastern time)",TimeFormat2(nextWebinarTime_est));if((t1.getTime()-nextWebinarTime_est.getTime())/60000>min_interval){addOption("webinar_times",TimeFormat1(t1)+" (US Eastern time)",TimeFormat2(t1));}
if((t2.getTime()-nextWebinarTime_est.getTime())/60000>min_interval){addOption("webinar_times",TimeFormat1(t2)+" (US Eastern time)",TimeFormat2(t2));}
if((t3.getTime()-nextWebinarTime_est.getTime())/60000>min_interval){addOption("webinar_times",TimeFormat1(t3)+" (US Eastern time)",TimeFormat2(t3));}
if((t4.getTime()-nextWebinarTime_est.getTime())/60000>min_interval){addOption("webinar_times",TimeFormat1(t4)+" (US Eastern time)",TimeFormat2(t4));}}else{addOption("webinar_times","Select your Time","");addOption("webinar_times",TimeFormat1(t1)+" (US Eastern time)",TimeFormat2(t1));addOption("webinar_times",TimeFormat1(t2)+" (US Eastern time)",TimeFormat2(t2));addOption("webinar_times",TimeFormat1(t3)+" (US Eastern time)",TimeFormat2(t3));addOption("webinar_times",TimeFormat1(t4)+" (US Eastern time)",TimeFormat2(t4));}
$("#webinar_times").show();$('.optin-container').hide();$("input[name=date]").val(document.getElementById("webinar_dates").value);}else{$("#webinar_times").hide();$('.optin-container').hide();$('#webinar-modal .reveal-title h3').html("Select a date and time for your webinar.");}}
function timeSelect(){if(document.getElementById("webinar_times").value!=""){$('.form-loading').show();setTimeout(function(){$('.form-loading').hide();$('#webinar-modal .reveal-title h3').html("Enter your Name and Email below to register for the webinar and secure your seat.");$('.optin-container').fadeIn('fast');$("input[name=time]").val(document.getElementById("webinar_times").value);},1500);}else{$('.optin-container').hide();$('#webinar-modal .reveal-title h3').html("Select a date and time for your webinar.");}}
function processRegistrationForm()
{$('.reserving-seat-loading').show();$('#registrationForm').hide();$('#webinar-modal .reveal-title h3').hide();var error=false;var date=document.getElementById("date").value;var time=document.getElementById("time").value;var name=document.getElementById("fn").value;var email=document.getElementById("email").value;if(date==""||time==""||name==""||email=="")
{error=true;}
if(error)
{$('.reserving-seat-loading').hide();$('#registrationForm').show();$('#webinar-modal .reveal-title h3').show();$("#btn-schedule-webinar").html("Yes! Reserve my seat now");$("#btn-schedule-webinar").prop("disabled",false);return false;}
$("#btn-schedule-webinar").prop("disabled",true);$("#btn-schedule-webinar").html("Processing...");if(document.getElementById('webinar_dates').selectedIndex==1&&document.getElementById('webinar_times').selectedIndex==1&&(nextWebinarTime.getTime()-now.getTime())/60000<=jit_interval){$("#jit").val(1);}
return true;}
function exitIntent()
{$("#uid").val("p2c11902f23");}